from __future__ import annotations

import os
import re
import time
from pathlib import Path

from .tiers import (
    Confidence,
    MemoryEntry,
    MemoryTier,
    entry_id,
    normalize_confidence,
)

_ENTRY_RE = re.compile(
    r"^-\s+"
    r"(?:`(?P<id>[^`]+)`\s+)?"
    r"(?:\[(?P<conf>[^\]]+)\]\s+)?"
    r"(?P<text>.*?)"
    r"(?:\s+\{tags:\s*(?P<tags>[^}]*)\})?"
    r"\s*$"
)

_SECRET_PATTERNS = (
    re.compile(r"hf_[A-Za-z0-9]{16,}"),
    re.compile(r"sk-[A-Za-z0-9]{16,}"),
    re.compile(r"AIza[0-9A-Za-z_\-]{20,}"),
    re.compile(r"ghp_[A-Za-z0-9]{20,}"),
    re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\"client_secret\"\s*:"),
)

_SECRET_ENV_KEYS = (
    "HF_TOKEN",
    "HUGGING_FACE_HUB_TOKEN",
    "SOPHON_OVERLEAF_GIT_TOKEN",
    "OVERLEAF_GIT_TOKEN",
    "SOPHON_OBSIDIAN_API_KEY",
    "OBSIDIAN_API_KEY",
    "OBSIDIAN_API_TOKEN",
    "SOPHON_GOOGLE_CSE_KEY",
    "SOPHON_LM_STUDIO_API_KEY",
    "SOPHON_OPENAI_API_KEY",
    "OPENAI_API_KEY",
    "SOPHON_ANTHROPIC_API_KEY",
    "ANTHROPIC_API_KEY",
    "SOPHON_GEMINI_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "SOPHON_TWITCH_CLIENT_SECRET",
    "SOPHON_EBAY_CLIENT_SECRET",
)

_FACTS_SEED = (
    "# Durable facts\n\n"
    "High-trust, human-approved facts about this project. "
    "Promote from scratch with `/memory promote <id>`.\n"
    "Confidence: [observed] verified, [decided] chosen.\n\n"
)

_PROCEDURES_SEED = (
    "# Procedures\n\n"
    "Pointers to Lembas skills and slash recipes. One bullet per procedure.\n\n"
    "- `perror1` [decided] After a failed command or the same approach twice, "
    "write an observed scratch note (tag error,repeat), call memory_propose, "
    "and ask the user to Accept in Review. Do not retry the same failed step "
    "without a new hypothesis. Search memory first.\n"
    "- `pskill1` [decided] Skills live in `.sophon/skills` (SKILL.md format). "
    "Call skill_list before a specialized workflow, skill_read before following "
    "one. Create with `/skill create <name>`, Accept in Review. Do not invent "
    "skills that are not listed.\n"
)

_STATE_SEED = (
    "# Memory state\n\n"
    "Catalog of what this project remembers. Regenerated by `/memory status`.\n\n"
)

_CONSTRAINTS_SEED = (
    "# Memory constraints\n\n"
    "What must never be stored in memory files.\n\n"
    "Default deny: API tokens, OAuth client secrets, private keys, `.env` values.\n\n"
    "## Deny literals\n\n"
    "Add one bullet per literal string that must never be stored.\n\n"
)


def _tags_to_text(tags: list[str]) -> str:
    cleaned = [t.strip() for t in tags if t.strip()]
    if not cleaned:
        return ""
    return " {tags: " + ", ".join(cleaned) + "}"


def render_entry_line(entry: MemoryEntry) -> str:
    entry.with_id()
    return f"- `{entry.id}` [{entry.confidence}] {entry.text.strip()}{_tags_to_text(entry.tags)}"


def parse_entries(text: str, tier: MemoryTier, default_conf: Confidence) -> list[MemoryEntry]:
    entries: list[MemoryEntry] = []
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip().startswith("- "):
            continue
        match = _ENTRY_RE.match(line.strip())
        if match is None:
            continue
        body = (match.group("text") or "").strip()
        if not body:
            continue
        conf = normalize_confidence(match.group("conf"), default_conf)
        tags_raw = match.group("tags") or ""
        tags = [t.strip() for t in tags_raw.split(",") if t.strip()]
        eid = (match.group("id") or "").strip() or entry_id(tier, body)
        entries.append(
            MemoryEntry(
                id=eid,
                tier=tier,
                text=body,
                confidence=conf,
                source="human",
                tags=tags,
            )
        )
    return entries


class MarkdownMemoryStore:
    def __init__(self, root: Path) -> None:
        self.dir = Path(root)
        self.scratch_dir = self.dir / "scratch"
        self.facts_path = self.dir / "facts.md"
        self.procedures_path = self.dir / "procedures.md"
        self.state_path = self.dir / "MEMORY-STATE.md"
        self.constraints_path = self.dir / "memory-constraints.md"

    def ensure_scaffold(self) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        self.scratch_dir.mkdir(parents=True, exist_ok=True)
        seeds = (
            (self.facts_path, _FACTS_SEED),
            (self.procedures_path, _PROCEDURES_SEED),
            (self.state_path, _STATE_SEED),
            (self.constraints_path, _CONSTRAINTS_SEED),
        )
        for path, seed in seeds:
            if not path.exists():
                path.write_text(seed, encoding="utf-8")

    def scratch_path(self, session_id: str) -> Path:
        safe = re.sub(r"[^A-Za-z0-9_.-]", "_", session_id or "session")
        return self.scratch_dir / f"{safe}.md"

    def read_scratch(self, session_id: str) -> list[MemoryEntry]:
        path = self.scratch_path(session_id)
        if not path.is_file():
            return []
        return parse_entries(path.read_text(encoding="utf-8", errors="replace"), "working", "hypothesis")

    def write_scratch(self, session_id: str, entries: list[MemoryEntry]) -> None:
        path = self.scratch_path(session_id)
        header = f"# Session scratch ({session_id})\n\n"
        body = "\n".join(render_entry_line(e) for e in entries)
        path.write_text(header + body + ("\n" if body else ""), encoding="utf-8")

    def append_scratch(self, session_id: str, entry: MemoryEntry) -> MemoryEntry:
        entry.with_id()
        existing = self.read_scratch(session_id)
        if any(e.id == entry.id for e in existing):
            return entry
        existing.append(entry)
        self.write_scratch(session_id, existing)
        return entry

    def clear_scratch(self, session_id: str) -> int:
        existing = self.read_scratch(session_id)
        self.write_scratch(session_id, [])
        return len(existing)

    def read_facts(self) -> list[MemoryEntry]:
        if not self.facts_path.is_file():
            return []
        return parse_entries(self.facts_path.read_text(encoding="utf-8", errors="replace"), "semantic", "decided")

    def render_facts(self, entries: list[MemoryEntry]) -> str:
        body = "\n".join(render_entry_line(e) for e in entries)
        return _FACTS_SEED + body + ("\n" if body else "")

    def write_facts(self, entries: list[MemoryEntry]) -> None:
        self.facts_path.write_text(self.render_facts(entries), encoding="utf-8")

    def read_procedures(self) -> list[MemoryEntry]:
        if not self.procedures_path.is_file():
            return []
        return parse_entries(self.procedures_path.read_text(encoding="utf-8", errors="replace"), "procedural", "decided")

    def deny_literals(self) -> list[str]:
        if not self.constraints_path.is_file():
            return []
        text = self.constraints_path.read_text(encoding="utf-8", errors="replace")
        literals: list[str] = []
        in_section = False
        for raw in text.splitlines():
            line = raw.strip()
            if line.lower().startswith("## deny literals"):
                in_section = True
                continue
            if in_section and line.startswith("## "):
                break
            if in_section and line.startswith("- "):
                literal = line[2:].strip().strip("`")
                if literal and not literal.lower().startswith("add one bullet"):
                    literals.append(literal)
        return literals

    def contains_secret(self, text: str) -> bool:
        probe = text or ""
        for pattern in _SECRET_PATTERNS:
            if pattern.search(probe):
                return True
        for key in _SECRET_ENV_KEYS:
            value = os.environ.get(key, "").strip()
            if value and len(value) >= 8 and value in probe:
                return True
        lowered = probe.lower()
        for literal in self.deny_literals():
            if literal.lower() in lowered:
                return True
        return False

    def redact(self, text: str) -> tuple[str, bool]:
        redacted = text or ""
        changed = False
        for pattern in _SECRET_PATTERNS:
            new = pattern.sub("[redacted]", redacted)
            if new != redacted:
                changed = True
                redacted = new
        for key in _SECRET_ENV_KEYS:
            value = os.environ.get(key, "").strip()
            if value and len(value) >= 8 and value in redacted:
                redacted = redacted.replace(value, "[redacted]")
                changed = True
        for literal in self.deny_literals():
            if literal and literal in redacted:
                redacted = redacted.replace(literal, "[redacted]")
                changed = True
        return redacted, changed


def now_ts() -> float:
    return time.time()
